name: "Snowflake Terraform Demo Workflow"

on:
  push:
    branches:
      - main

jobs:
  snowflake-terraform-demo:
    name: "Snowflake Terraform Demo Job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.API_TOKEN }}
          
      - name: Install SnowSQL
        run: |
          curl -o snowsql.exe -L https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/windows_x86_64/snowsql.exe
          .\snowsql.exe -n # This runs the SnowSQL installer in non-interactive mode
          setx PATH "%PATH%;C:\Program Files\SnowSQL" # Add SnowSQL to the PATH

      # Verify SnowSQL Installation
      - name: Verify SnowSQL
        run: snowsql -v

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        
